### ISSUE TITLE
Google Translation API issue: Cannot read property 'forEach' of null Url

### ISSUE THREAD

**Issue by wisdmyogeshshirsath** [funkyremi/vscode-google-translate#51]
Google Translation API issue: Cannot read property 'forEach' of null Url: https://translate.google.com/_/TranslateWebserverUi/data/batchexecute?rpcids=MkEWBc&f.sid=6924383159705700448&bl=boq_translate-webserver_20210106.08_p0&hl=en-US&soc-app=1&soc-platform=1&soc-device=1&_reqid=6775&rt=c

**Comment by chinmay2505** [comment]
Same error here

**Comment by funkyremi** [comment]
Can you provide steps to reproduce please? Is it always with a specific string?

**Comment by wisdmyogeshshirsath** [comment]
Try to translate multi selection lines.

**Comment by funkyremi** [comment]
It’s working for me. Is it always failing for you? Can you provide the exact strings that are failing?

**Comment by brandongregoryscott** [comment]
I'm hitting this as well, with single or multiple lines. On extension v1.4.12, VSCode 1.52.1

![nh3qGVEMHm](https://user-images.githubusercontent.com/11774799/106051170-19e9d000-60b6-11eb-94a4-84e36f4daea6.gif)

**Comment by ConeCafe** [comment]
same error here, it works in some lines and not with others (using to translate from english to spanish). 
There doesn't seem to be a pattern

**Comment by ImADrafter** [comment]
Same error for same languages (from english to spanish) using multiselection. Any updates on this ?

**Comment by funkyremi** [comment]
Hi, it should be fixed with the latest version 1.4.13.
Feel free to reopen if needed.

**Comment by denbon05** [comment]
![image](https://github.com/funkyremi/vscode-google-translate/assets/58662935/d8c2a92b-6a7f-4590-8f7c-a027b5b391a3)

still facing this error
<pre>
Google Translation API issue: Cannot read properties of null (reading '1') Url: 
https://translate.google.com/_/TranslateWebserverUi/data/batchexecute?
rpcids=MkEWBc&f.sid=-5991602115342472001&bl=boq_translate-webserver_20230509.05_p0&hl=en-US&soc-app=1&soc-platform=1&soc-device=1&_reqid=1425&rt=c
</pre>

**Comment by umitkabuli** [comment]
Translate failed, Error message: 'Cannot read properties of null (reading '1')
Url: https://translate.google.com/_/TranslateWebserverUi/data/batchexecute?rpcids=MkEWBc&f.sid=1958792426535229329&bl=boq_translate-webserver_20230830.06_p0&hl=en-US&soc-app=1&soc-platform=1&soc-device=1&_reqid=4018&rt=c'. Please post an issues for me.

**Comment by itsaplev** [comment]
still here
